### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by tmankendall** [tezos/tezos#11]
Looking at the config file, I fail to see why many of these parameters are configurable by the node operator. If this network aims to be avoid branches, choosing instead to evolve through voting, why are node operators allowed to configure everything from peer connections needed to anticipated proof of work? Shouldn't this all be set by the network, and only changed through public voting?

**Comment by tezos** [comment]
These parameters aren't related to the consensus. The proof of work parameter you see is related to which node you will be willing to talk to. Each node has a little proof of work stamp,  because relying on the scarcity of IPv4 won't last (or will it... ). 

While it's possible that a set of nodes could require a very high level and isolate themselves from the network, this can also happen with any blockchain. Nodes have an incentive to stay in consensus and thus not to disconnect themselves from the main cluster of nodes.

**Comment by tmankendall** [comment]
nonetheless interesting choice to still give some power to the miners given the whole idea is to give it back to the owners. As someone who has obviously thought less about this than you, I will defer to your advise, but seems like taking away all potential for node separation would be a good idea.

Just glad to hear the config has nothing to do with consensus!

Sorry for the newbie question! Thanks for being so responsive and patient!
