### ISSUE TITLE
ALPHANET: Unclassified error: Prevalidation.Parse_error. Was the error registered?

### ISSUE THREAD

**Issue by catsigma** [tezos/tezos#124]
I'm originating this [script](https://github.com/catsigma/bettingwin/blob/master/contracts/token.build.tz).

```
> alphanet client typecheck program container:token.build.tz
Well typed

> alphanet client originate contract test_token1 for my_identity transferring 2.01 from my_account running container:token.build.tz -init '(Pair (Pair (Map ) Unit) (Pair (Map ) (Pair 100000 (Pair 2 (Pair "BettingWin" "BTW")))))'
Got the source's manager keys (my_identity).
Error:
  Unclassified error: Prevalidation.Parse_error. Was the error registered?

Error:
  The operation cannot be parsed

Fatal error: origination simulation failed
```
How can I fix my contract?

**Comment by catsigma** [comment]
using 
```
alphanet client originate contract test_contract0 for my_identity transferring 2.01 from my_account running container:token.build.tz -init '(Pair (Pair (Map ) Unit) (Pair (Map ) (Pair 100000 (Pair 2 (Pair "x" "y")))))'
```

**Comment by MiloDavis** [comment]
Firstly, thank you for reporting this error along with all of the steps to reproduce. The issue is with the size of the operation we're generating to originate your contract. The operation to originate this contract was 17553 bytes, which exceeded the maximum allowed operation size we have set currently (16384 bytes). We're going to look at increasing the maximum operation size and play with the representation of Michelson programs to make writing contracts like this one possible.
